### ISSUE TITLE
System.DllNotFoundException: 'DLL 'python37'을(를) 로드할 수 없습니다. 지정된 모듈을 찾을 수 없습니다. (예외가 발생한 HRESULT: 0x8007007E)'

### ISSUE THREAD

**Issue by k0kao** [taromati/Keras.Net_Sample#1]
readme에 있는 내용대로 설치및 세팅을 다했는데도 불구하고 해당부분에서 

**var model = Model.LoadModel("keras_model.h5");**

아래와 같은 오류가납니다.
-----------------------------------------------------------------------------------------------------------------------------
처리되지 않은 'System.DllNotFoundException' 형식의 예외가 mscorlib.dll에서 발생했습니다.
DLL 'python37'을(를) 로드할 수 없습니다. 지정된 모듈을 찾을 수 없습니다. (예외가 발생한 HRESULT: 0x8007007E)
-----------------------------------------------------------------------------------------------------------------------------

window 10 64bit환경
파이썬 64bit설치,환경변수까지 지정완료
pip 관련 라이브러리 설치완료.

누겟도 전부 다 최신으로 업데이트했습니다.

**Comment by taromati** [comment]
python37은 3.7버전을 뜻하는데 keras.net이 파이썬 3.7로 버전을 올린것같습니다 파이썬 버전을 올려보세요

**Comment by k0kao** [comment]
> python37은 3.7버전을 뜻하는데 keras.net이 파이썬 3.7로 버전을 올린것같습니다 파이썬 버전을 올려보세요

파이썬은 Python 3.8.4rc1 - June 30, 2020 해당버전 사용중입니다.

혹시 taromati님 PC에서는 해당소스 정상적으로 아직까지 작동하시나요??

**Comment by taromati** [comment]
절대 파이썬 버전 최신 쓰시면 안됩니다 케라스에 맞는 버전 쓰셔야해요
3.7로 내리고 테스트 해보세요
혹시나 아나콘다 쓰신다면 아나콘다 지우시고 파이썬 윈도우 배포판 쓰셔야하고요
지금 윈도우 머신이 없어 오늘 밤늦게나 테스트 가능한 상황이라 직접 해보시는게 빠를거같네요

**Comment by k0kao** [comment]
> 절대 파이썬 버전 최신 쓰시면 안됩니다 케라스에 맞는 버전 쓰셔야해요
> 3.7로 내리고 테스트 해보세요
> 혹시나 아나콘다 쓰신다면 아나콘다 지우시고 파이썬 윈도우 배포판 쓰셔야하고요
> 지금 윈도우 머신이 없어 오늘 밤늦게나 테스트 가능한 상황이라 직접 해보시는게 빠를거같네요

먼저 몇달전 프로젝트인데도 불구하고 이렇게 답변해주셔서 감사합니다.

파이썬 3.7로내리고 다시한번 작업해보겠습니다!

그리고 테스트하시고 알려주시면 감사합니다!!ㅎㅎ

**Comment by k0kao** [comment]
> 절대 파이썬 버전 최신 쓰시면 안됩니다 케라스에 맞는 버전 쓰셔야해요
> 3.7로 내리고 테스트 해보세요
> 혹시나 아나콘다 쓰신다면 아나콘다 지우시고 파이썬 윈도우 배포판 쓰셔야하고요
> 지금 윈도우 머신이 없어 오늘 밤늦게나 테스트 가능한 상황이라 직접 해보시는게 빠를거같네요


기존 파이썬 3.8삭제후 3.7설치후

tensorflow             2.2.0
Keras                  2.4.3
Keras-Preprocessing    1.1.2

pip로 필요한것들 설치 다한뒤 
디버그 실행하면 동일한 위치에 다른 오류가 발생합니다.

**var model = Model.LoadModel("C:/keras_model.h5");**

----------------------------------------------------------------------------------

System.BadImageFormatException: '프로그램을 잘못된 형식으로 로드하려고 했습니다. (예외가 발생한 HRESULT: 0x8007000B)'

-----------------------------------------------------------------------------------------

**Comment by k0kao** [comment]
> 절대 파이썬 버전 최신 쓰시면 안됩니다 케라스에 맞는 버전 쓰셔야해요
> 3.7로 내리고 테스트 해보세요
> 혹시나 아나콘다 쓰신다면 아나콘다 지우시고 파이썬 윈도우 배포판 쓰셔야하고요
> 지금 윈도우 머신이 없어 오늘 밤늦게나 테스트 가능한 상황이라 직접 해보시는게 빠를거같네요

해결했습니다!
혹시 Vb.net에서는 Predict를 .Tostring()으로 작성하면
.tostring()으로 계속 자동 변경되서 안되는데 어떻게 해야지 predict값을 string으로 받아올수있을까요?
참고로 C#에서는 Tostring형식으로 잘됩니다
